--- 
cached_config: 
  article: 
    url: http://www.example.com/article
    api: 
      url: 
        comments: articles/:article_id/comments
    database: 
      adapter: mysql
      username: root
      database: article_development
      host: localhost
      password: root
  cache_test: 
    url: http://test.com
url: http://www.example.com/test_app
api: 
  url: 
    list: /posts
other: some other
readonly_for_test: 
  comments: 
    string: title
